# Generated by Django 5.2.17 on 2026-08-06 01:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('passphrase_hash', models.CharField(max_length=255)),
                ('hide_card', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color_value', models.PositiveSmallIntegerField(choices=[(1, 'Red'), (2, 'Blue'), (4, 'Green'), (8, 'Orange'), (16, 'Purple'), (32, 'Navy'), (64, 'Teal'), (128, 'Pink'), (256, 'Brown'), (512, 'Yellow')], default=1)),
                ('is_spectator', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='rooms.room')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.PositiveSmallIntegerField(default=5)),
                ('cols', models.PositiveSmallIntegerField(default=5)),
                ('board_type', models.CharField(choices=[('fixed', 'Fixed Board'), ('randomized', 'Randomized')], max_length=20)),
                ('lockout_mode', models.CharField(choices=[('non_lockout', 'Non-Lockout'), ('lockout', 'Lockout')], default='non_lockout', max_length=20)),
                ('seed', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='rooms.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('chat', 'Chat'), ('goal', 'Goal'), ('color', 'Color'), ('revealed', 'Revealed'), ('connection', 'Connection'), ('new_card', 'New Card')], max_length=20)),
                ('player_color', models.PositiveSmallIntegerField(choices=[(1, 'Red'), (2, 'Blue'), (4, 'Green'), (8, 'Orange'), (16, 'Purple'), (32, 'Navy'), (64, 'Teal'), (128, 'Pink'), (256, 'Brown'), (512, 'Yellow')])),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rooms.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rooms.room')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveSmallIntegerField()),
                ('col', models.PositiveSmallIntegerField()),
                ('goal', models.CharField(max_length=255)),
                ('colors', models.PositiveSmallIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squares', to='rooms.game')),
            ],
            options={
                'ordering': ['row', 'col'],
                'constraints': [models.UniqueConstraint(fields=('game', 'row', 'col'), name='unique_square_position')],
            },
        ),
    ]
